import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideNav from "@/components/SideNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-orange-50`}
      >
        {/* Mobile SideNav (only visible on mobile) */}
        <div className="md:hidden">
          <SideNav />
        </div>
        
        {/* Desktop layout (hidden on mobile) */}
        <div className="hidden md:flex h-screen">
          <div className="w-16 flex-shrink-0 z-50 relative">
            <SideNav />
          </div>
          
          <div className="flex-1">
            {children}
          </div>
        </div>
        
        {/* Mobile content (only visible on mobile) */}
        <main className="md:hidden min-h-screen">
          <div className="pt-16">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}